[[redirects]]
from = "/getNumOfCoins"
to = "https://kmcblockchain.herokuapp.com/getNumOfCoins"

[[redirects]]
from = "/quiz"
to = "https://kmcblockchain.herokuapp.com/quiz"

[[redirects]]
from = "/posts"
to = "https://kmcblockchain.herokuapp.com/posts"

[[redirects]]
from = "/initiateAccountInDB"
to = "https://kmcblockchain.herokuapp.com/initiateAccountInDB"

[[redirects]]
from = "/withdraw"
to = "https://kmcblockchain.herokuapp.com/withdraw"





