[[redirects]]
from = "/getNumOfCoins"
to = "https://kmcblockchain.herokuapp.com/getNumOfCoins"

[[redirects]]
from = "/quiz"
to = "https://kmcblockchain.herokuapp.com/quiz"

[[redirects]]
from = "/posts/"
to = "https://kmcblockchain.herokuapp.com/posts/:splat"
status = 200
force = true


[[redirects]]
from = "/initiateAccountInDB"
to = "https://kmcblockchain.herokuapp.com/initiateAccountInDB"

[[redirects]]
from = "/withdraw"
to = "https://kmcblockchain.herokuapp.com/withdraw"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "https://kmcblockchain.herokuapp.com/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"




